##Makefile is simple task, where it runs some commands in the background
Help:
	@grep '####' Makefile | grep -v grep | sed -e 's/####//'
One: #### Target One
	@echo Ashu
Two: #### Target Two
	@echo Chibu


